
spring:
  application:
    name: email-service
  datasource:
    url: jdbc:mysql://emailsdb:3307/emails
    username: root
    password: password12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: true
  kafka:
    consumer:
      group-id: email-service
sendgrid:
  api.key: ${SENDGRID_API_KEY}
  from.email: no-reply@growme.com
  from.name: GrowMe
