spring:
  application:
    name: email-service
  datasource:
    url: jbdc:mysql://emailsdb:3307/emails
    username: root
    password: password12345
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
