
spring:
  application:
    name: user-service
  datasource:
    url: jbdc:mysql://emailsdb:3307/growmeusers
    username: root
    password: password12345
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8088"
  sql:
    init:
      mode: aweys

  kafka:
    consumer:
      group-id: user-service
